DROP TABLE EMPLOYEE CASCADE CONSTRAINTS;

CREATE TABLE
    EMPLOYEE (
        ID VARCHAR(20),
        NAME VARCHAR(50),
        ADDRESS VARCHAR(100),
        HIRE_DATE DATE,
        CONSTRAINT EMPLOYEE_ID_PK PRIMARY KEY (ID)
    );