CREATE
OR REPLACE FUNCTION GETEXPERIENCE (GIVENID IN EMPLOYEE.ID % TYPE) RETURN DOUBLE PRECISION IS EXPERIENCE DOUBLE PRECISION
BEGIN
SELECT
    ROUND(ABS((CURRENT_DATE - HIRE_DATE) / 365), 2) INTO EXPERIENCE
FROM
    EMPLOYEE
WHERE
    ID = GIVENID;

RETURN EXPERIENCE;

END;

/