DROP TABLE EMPLOYEE CASCADE CONSTRAINTS;

CREATE TABLE EMPLOYEE(
    EMPNO VARCHAR(20),
    FIRSTNAME VARCHAR(40),
    LASTNAME VARCHAR(40),
    SALARY DOUBLE PRECISION,
    DESIGNATION VARCHAR(10),
    DEPTID VARCHAR(10)
);

CREATE OR REPLACE TRIGGER EMPNAMEUPPER BEFORE
    INSERT OR UPDATE ON EMPLOYEE FOR EACH ROW
BEGIN
    :NEW.FIRSTNAME := UPPER(:NEW.FIRSTNAME);
END;
/

INSERT INTO EMPLOYEE VALUES(
    '11',
    'f1',
    'L1',
    2000,
    'D1',
    '22'
);

DECLARE
    CURSOR EMPDETAILS IS
        SELECT
            *
        FROM
            EMPLOYEE;
BEGIN
    FOR EMPLOYEE IN EMPDETAILS LOOP
        DBMS_OUTPUT.PUT_LINE(EMPLOYEE.FIRSTNAME);
    END LOOP;
END;
/