-- @creation.sql

DROP TABLE WORKS_ON;

DROP TABLE PROJECT;

DROP TABLE DEPT;

DROP TABLE EMPLOYEE;

CREATE TABLE EMPLOYEE(
    SSN INT,
    NAME VARCHAR(40),
    SEX VARCHAR(1),
    ADDRESS VARCHAR(100),
    SALARY DOUBLE PRECISION,
    DEPT INT,
    DESIGNATION VARCHAR(20),
    SUPERVISORSSN INT,
    CONSTRAINT EMPLOYEE__PK PRIMARY KEY(SSN)
);

CREATE TABLE DEPT(
    DEPT_NUMBER INT,
    NAME VARCHAR(40),
    MANAGERSSN INT,
    MANAGER_DOB DATE,
    LOCATION VARCHAR(20),
    CONSTRAINT DEPARTMENT_PK PRIMARY KEY(DEPT_NUMBER),
    CONSTRAINT DEPT_MANAGERSSN_PK FOREIGN KEY(MANAGERSSN) REFERENCES EMPLOYEE(SSN)
);

CREATE TABLE PROJECT(
    PROJECT_NUMBER INT,
    NAME VARCHAR(30),
    LOCATION VARCHAR(20),
    CONTROLLING_DEPARTMENT INT,
    BUDGET DOUBLE PRECISION,
    CONSTRAINT PROJECT_PK PRIMARY KEY(PROJECT_NUMBER),
    CONSTRAINT PROJECT_DEPT_FK FOREIGN KEY(CONTROLLING_DEPARTMENT) REFERENCES DEPT(DEPT_NUMBER)
);

CREATE TABLE WORKS_ON(
    SSN INT,
    PROJECT_NUM INT,
    HOURS INT,
    CONSTRAINT WORKS_ON_PK PRIMARY KEY(SSN, PROJECT_NUM),
    CONSTRAINT WORKS_ON_EMPLOYEE_FK FOREIGN KEY(SSN) REFERENCES EMPLOYEE(SSN),
    CONSTRAINT WORKS_ON_PROJECT_FK FOREIGN KEY(PROJECT_NUM) REFERENCES PROJECT(PROJECT_NUMBER)
);