SET SERVEROUTPUT ON

--file_name : q4.sql
DECLARE
    V_SQL VARCHAR2(4000);
BEGIN
    FOR C IN (
        SELECT
            COLUMN_NAME
        FROM
            ALL_TAB_COLUMNS
        WHERE
            TABLE_NAME = 'EMPLOYEE2'
    ) LOOP
        V_SQL := 'COLUMN '
            || C.COLUMN_NAME
            || ' FORMAT A20';
        DBMS_OUTPUT.PUT_LINE(V_SQL);
    END LOOP;
    FOR C IN (
        SELECT
            COLUMN_NAME
        FROM
            ALL_TAB_COLUMNS
        WHERE
            TABLE_NAME = 'GUIDE'
    ) LOOP
        V_SQL := 'COLUMN '
            || C.COLUMN_NAME
            || ' FORMAT A20';
        DBMS_OUTPUT.PUT_LINE(V_SQL);
    END LOOP;
    FOR C IN (
        SELECT
            COLUMN_NAME
        FROM
            ALL_TAB_COLUMNS
        WHERE
            TABLE_NAME = 'ADMIN'
    ) LOOP
        V_SQL := 'COLUMN '
            || C.COLUMN_NAME
            || ' FORMAT A20';
        DBMS_OUTPUT.PUT_LINE(V_SQL);
    END LOOP;
END;
/

SET LINESIZE 80

--COLUMN FORMATTING
COLUMN ID FORMAT 99

COLUMN NAME FORMAT A17

COLUMN ADDRESS FORMAT A15

-- COLUMN SALARY FORMAT 99
COLUMN LANGUAGES FORMAT A30

COLUMN COUNTRIES FORMAT A30

COLUMN COMPSKILLS FORMAT A30

COLUMN OFFICESKILLS FORMAT A30

DROP TABLE EMPLOYEE2;

DROP TABLE GUIDE;

DROP TABLE ADMIN;

DROP TYPE GUIDE_T;

DROP TYPE ADMIN_T;

DROP TYPE LANGUAGE_VARRAY_TYPE;

-- DROP TYPE LANGUAGE_T;
DROP TYPE COUNTRY_VARRAY_TYPE;

-- DROP TYPE COUNTRY_T;
DROP TYPE OFFICESKILLS_VARRAY_TYPE;

-- DROP TYPE OFFICESKILLS_T;
DROP TYPE COMPSKILLS_VARRAY_TYPE;

-- DROP TYPE COMPSKILLS_T;
DROP TYPE EMPLOYEE_T;

--EMPLOYEE
CREATE OR REPLACE TYPE EMPLOYEE_T AS
    OBJECT(
        ID NUMBER,
        NAME VARCHAR(20),
        ADDRESS VARCHAR(20),
        SALARY NUMBER,
        STATIC PROCEDURE INSERT_EMPLOYEE(EID NUMBER, ENAME VARCHAR, EADDRESS VARCHAR, SALARY NUMBER),
        STATIC PROCEDURE DELETE_EMPLOYEE(EID NUMBER)
    )NOT FINAL;
/

CREATE TABLE EMPLOYEE2 OF EMPLOYEE_T;

BEGIN
    DBMS_OUTPUT.PUT_LINE(CHR(10)
        ||'DESCRIBE EMPLOYEE2');
END;
/

DESC EMPLOYEE2;

CREATE OR REPLACE TYPE BODY EMPLOYEE_T AS
    STATIC PROCEDURE INSERT_EMPLOYEE(
        EID NUMBER,
        ENAME VARCHAR,
        EADDRESS VARCHAR,
        SALARY NUMBER
    ) IS
    BEGIN
        INSERT INTO EMPLOYEE2 VALUES (
            EID,
            ENAME,
            EADDRESS,
            SALARY
        );
    END INSERT_EMPLOYEE;
    STATIC PROCEDURE DELETE_EMPLOYEE(
        EID NUMBER
    ) IS
    BEGIN
        DELETE FROM EMPLOYEE2
        WHERE
            ID = EID;
    END DELETE_EMPLOYEE;
END;
/

--LANGUAGE
-- CREATE OR REPLACE TYPE LANGUAGE_T AS OBJECT(
-- LANGUAGE VARCHAR(20)
-- );
-- /
CREATE TYPE LANGUAGE_VARRAY_TYPE AS
    VARRAY(
        3
    ) OF VARCHAR(
        20
    );
/

--COUNTRY
-- CREATE OR REPLACE TYPE COUNTRY_T AS OBJECT(
-- COUNTRY VARCHAR(20)
-- );
-- /
CREATE TYPE COUNTRY_VARRAY_TYPE AS
    VARRAY(
        3
    ) OF VARCHAR(
        20
    );
/

--GUIDE
CREATE OR REPLACE TYPE GUIDE_T UNDER EMPLOYEE_T(
    LANGUAGES LANGUAGE_VARRAY_TYPE,
    COUNTRIES COUNTRY_VARRAY_TYPE,
    STATIC PROCEDURE INSERT_GUIDE(GID NUMBER, LANGUAGES LANGUAGE_VARRAY_TYPE, COUNTRIES COUNTRY_VARRAY_TYPE),
    STATIC PROCEDURE DELETE_GUIDE(GID NUMBER)
);
/

CREATE TABLE GUIDE OF GUIDE_T;

BEGIN
    DBMS_OUTPUT.PUT_LINE(CHR(10)
        ||'DESCRIBE GUIDE');
END;
/

DESC GUIDE;

CREATE OR REPLACE TYPE BODY GUIDE_T AS
    STATIC PROCEDURE INSERT_GUIDE(
        GID NUMBER,
        LANGUAGES LANGUAGE_VARRAY_TYPE,
        COUNTRIES COUNTRY_VARRAY_TYPE
    ) IS
    BEGIN
        INSERT INTO GUIDE
            SELECT
                GID,
                EMPLOYEE2.NAME,
                EMPLOYEE2.ADDRESS,
                EMPLOYEE2.SALARY,
                LANGUAGES,
                COUNTRIES
            FROM
                EMPLOYEE2
            WHERE
                EMPLOYEE2.ID = GID;
    END INSERT_GUIDE;
    STATIC PROCEDURE DELETE_GUIDE(
        GID NUMBER
    ) IS
    BEGIN
        DELETE FROM GUIDE
        WHERE
            ID = GID;
    END DELETE_GUIDE;
END;
/

--COMPUTER SKILLS
-- CREATE OR REPLACE TYPE COMPSKILLS_T AS OBJECT(
-- COMPSKILL VARCHAR(20)
-- );
-- /
CREATE TYPE COMPSKILLS_VARRAY_TYPE AS
    VARRAY(
        3
    ) OF VARCHAR(
        20
    );
/

--OFFICE SKILLS
-- CREATE OR REPLACE TYPE OFFICESKILLS_T AS OBJECT(
-- OFFICESKILL VARCHAR(20)
-- );
-- /
CREATE TYPE OFFICESKILLS_VARRAY_TYPE AS
    VARRAY(
        3
    ) OF VARCHAR(
        20
    );
/

--ADMIN
CREATE OR REPLACE TYPE ADMIN_T UNDER EMPLOYEE_T(
    COMPSKILLS COMPSKILLS_VARRAY_TYPE,
    OFFICESKILLS OFFICESKILLS_VARRAY_TYPE,
    STATIC PROCEDURE INSERT_ADMIN(AID NUMBER, COMPSKILLS COMPSKILLS_VARRAY_TYPE, OFFICESKILLS OFFICESKILLS_VARRAY_TYPE),
    STATIC PROCEDURE DELETE_ADMIN(AID NUMBER)
);
/

CREATE TABLE ADMIN OF ADMIN_T;

BEGIN
    DBMS_OUTPUT.PUT_LINE(CHR(10)
        ||'DESCRIBE ADMIN');
END;
/

DESC ADMIN;

CREATE OR REPLACE TYPE BODY ADMIN_T AS
    STATIC PROCEDURE INSERT_ADMIN(
        AID NUMBER,
        COMPSKILLS COMPSKILLS_VARRAY_TYPE,
        OFFICESKILLS OFFICESKILLS_VARRAY_TYPE
    ) IS
    BEGIN
        INSERT INTO ADMIN(
            ID,
            NAME,
            ADDRESS,
            SALARY
        )
            SELECT
                AID,
                EMPLOYEE2.NAME,
                EMPLOYEE2.ADDRESS,
                EMPLOYEE2.SALARY
            FROM
                EMPLOYEE2
            WHERE
                EMPLOYEE2.ID = AID;
        INSERT INTO ADMIN(
            COMPSKILLS,
            OFFICESKILLS
        ) VALUES (
            COMPSKILLS,
            OFFICESKILLS
        );
    END INSERT_ADMIN;
    STATIC PROCEDURE DELETE_ADMIN(
        AID NUMBER
    ) IS
    BEGIN
        DELETE FROM ADMIN
        WHERE
            ID = AID;
    END DELETE_ADMIN;
END;
/

--INSERTING VALUES
SET LINESIZE 1000

SET FEEDBACK OFF

--Employee
DELETE FROM EMPLOYEE2;

EXEC EMPLOYEE_T.INSERT_EMPLOYEE(1, 'VIRAT KOHLI', 'DELHI', 20000000);

EXEC EMPLOYEE_T.INSERT_EMPLOYEE(2, 'ROHIT SHARMA', 'MUMBAI', 2000000);

EXEC EMPLOYEE_T.INSERT_EMPLOYEE(3, 'SURYA YADAV', 'MUMBAI', 1500000);

EXEC EMPLOYEE_T.INSERT_EMPLOYEE(4, 'ISHAN KISHAN', 'JHARKHAND', 1000000);

EXEC EMPLOYEE_T.INSERT_EMPLOYEE(5, 'PAT CUMMINGS', 'CANBERRA', 900000);

BEGIN
    DBMS_OUTPUT.PUT_LINE(CHR(10)
        ||'EMPLOYEE2');
END;
/

SELECT
    *
FROM
    EMPLOYEE2;

--Guide
DELETE FROM GUIDE;

EXEC GUIDE_T.INSERT_GUIDE(1, LANGUAGE_VARRAY_TYPE('Hindi', 'English', 'Marathi'),

COUNTRY_VARRAY_TYPE('India', 'USA', 'UK'));

EXEC GUIDE_T.INSERT_GUIDE(2, LANGUAGE_VARRAY_TYPE('Hindi', 'English', 'Bengali'),

COUNTRY_VARRAY_TYPE('India', 'Germany', 'Peru'));

EXEC GUIDE_T.INSERT_GUIDE(3, LANGUAGE_VARRAY_TYPE('Tamil', 'English', 'Telugu'),

COUNTRY_VARRAY_TYPE('Canada', 'France', 'Brazil'));

BEGIN
    DBMS_OUTPUT.PUT_LINE(CHR(10)
        ||'GUIDE');
END;
/

SELECT
    *
FROM
    GUIDE;

--Admin
DELETE FROM ADMIN;

EXEC

ADMIN_T.INSERT_ADMIN(4, COMPSKILLS_VARRAY_TYPE('Presentations', 'Spreadsheets', 'Photo

EDITING'), officeskills_varray_type('TIME MGMT','LEADERSHIP','COMMUNICATIONS'));

EXEC ADMIN_T.INSERT_ADMIN(5, COMPSKILLS_VARRAY_TYPE('Video

EDITING','PRESENTATIONS','DATABASE MGMT'),

OFFICESKILLS_VARRAY_TYPE('Schedulilng', 'Communications', 'Time Mgmt'));

BEGIN
    DBMS_OUTPUT.PUT_LINE(CHR(10)
        ||'ADMIN');
END;
/

SELECT
    *
FROM
    ADMIN;

--DELETING ADMIN
BEGIN
    DBMS_OUTPUT.PUT_LINE(CHR(9));
    DBMS_OUTPUT.PUT_LINE(CHR(9));
    DBMS_OUTPUT.PUT_LINE('=============================');
    DBMS_OUTPUT.PUT_LINE('DELETING... ID - 1');
    DBMS_OUTPUT.PUT_LINE('=============================');
END;
/

EXEC ADMIN_T.DELETE_ADMIN(2);

BEGIN
    DBMS_OUTPUT.PUT_LINE(CHR(10)
        ||'ADMIN');
END;
/

SELECT
    *
FROM
    ADMIN;

--DELETING GUIDE
BEGIN
    DBMS_OUTPUT.PUT_LINE(CHR(9));
    DBMS_OUTPUT.PUT_LINE(CHR(9));
    DBMS_OUTPUT.PUT_LINE('=============================');
    DBMS_OUTPUT.PUT_LINE('DELETING... ID - 2 AND ID - 3');
    DBMS_OUTPUT.PUT_LINE('=============================');
END;
/

EXEC GUIDE_T.DELETE_GUIDE(2);

EXEC GUIDE_T.DELETE_GUIDE(3);

BEGIN
    DBMS_OUTPUT.PUT_LINE(CHR(10)
        ||'GUIDE');
END;
/

SELECT
    *
FROM
    GUIDE;

--DELETING EMPLOYEE
BEGIN
    DBMS_OUTPUT.PUT_LINE(CHR(9));
    DBMS_OUTPUT.PUT_LINE(CHR(9));
    DBMS_OUTPUT.PUT_LINE('=============================');
    DBMS_OUTPUT.PUT_LINE('DELETING... ID - 2 AND ID - 3');
    DBMS_OUTPUT.PUT_LINE('=============================');
END;
/

EXEC EMPLOYEE_T.DELETE_EMPLOYEE(2);

EXEC EMPLOYEE_T.DELETE_EMPLOYEE(3);

BEGIN
    DBMS_OUTPUT.PUT_LINE(CHR(10)
        ||'EMPLOYEE2');
END;
/

SELECT
    *
FROM
    EMPLOYEE2;