CREATE TABLE CUSTOMER(
    CUS_CODE VARCHAR2(10),
    CUS_FNAME VARCHAR2(30),
    CUS_LNAME VARCHAR(30),
    CUS_BALANCE DOUBLE PRECISION,
    CONSTRAINT CUSTOMER_CUS_CODE_PK PRIMARY KEY(CUS_CODE)
);

CREATE TABLE INVOICE(
    INV_NO VARCHAR2(10),
    CUS_CODE VARCHAR2(10),
    INV_DATE DATE;

CUS_BALANCE DOUBLE PRECISION,

CONSTRAINT INVOICE_INV_NO_PK PRIMARY KEY(INV_NO),

CONSTRAINT INVOICE_CUS_CODE_FK FOREIGN KEY(CUS_CODE) REFERENCES CUSTOMER(CUS_CODE)

);

CREATE TABLE LINE(
    INV_NO VARCHAR2(10),
    LINE_NO VARCHAR2(10),
    P_CODE VARCHAR2(10),
    LINE_UNITS INTEGER,
    LINE_PRICE DOUBLE PRECISION,
    CONSTRAINT LINE_INV_NO_LINE_NO_PK PRIMARY KEY(INV_NO, LINE_NO),
    CONSTRAINT LINE_INV_NO_FK FOREIGN KEY(INV_NO) REFERENCES INVOICE(INV_NO)
);

CREATE TABLE PRODUCT(
    P_CODE VARCHAR2(10),
    P_DESC VARCHAR2(100),
    P_QOH INT,
    P_MIN DOUBLE PRECISION,
    P_PRICE DOUBLE PRECISION,
    V_CODE VARCHAR2(10),
);

CREATE TABLE VENDOR(
    V_CODE VARCHAR2(10),
    V_NAME VARCHAR2(30),
    V_CONTACT INT;

CONSTRAINT VENDOR_V_CODE_PK PRIMARY KEY(V_CODE);

)