SET LINESIZE 1000

COLUMN PROF_ID HEADING 'PROFESSOR|ID' FORMAT A10

COLUMN DEPT_ID HEADING 'DEPARTMENT|ID' FORMAT A10

COLUMN IS_HOD HEADING 'IS HOD' FORMAT A15

COLUMN PROG_CODE HEADING 'PROGRAMME|CODE' FORMAT A10

COLUMN PROG_NAME HEADING 'PROGRAMME|NAME' FORMAT A20

COLUMN PROG_PREAMBLE HEADING 'PROGRAMME|PREAMBLE' FORMAT A50

COLUMN SCODE HEADING 'SCHOOL|CODE' FORMAT A10

COLUMN SNAME HEADING 'STUDENT|NAME' FORMAT A20

COLUMN EMAIL HEADING 'STUDENT|EMAIL' FORMAT A20

COLUMN ADDRESS HEADING 'STUDENT|ADDRESS' FORMAT A30

COLUMN REG_NO HEADING 'STUDENT|REG NO' FORMAT A10

COLUMN PROF_NAME HEADING 'PROFESSOR|NAME' FORMAT A20

COLUMN SPECIALITY HEADING 'PROFESSOR|SPECIALITY' FORMAT A30

COLUMN CLS_CODE HEADING 'CLASS|CODE' FORMAT A10

COLUMN ROOM_NO HEADING 'ROOM NO' FORMAT 9999

COLUMN SLOT FORMAT A10

COLUMN DURATION FORMAT 99

COLUMN STIME HEADING 'STARTING|TIME' FORMAT A10

COLUMN ETIME HEADING 'END|TIME' FORMAT A10

COLUMN CRS_CODE HEADING 'COURSE|CODE' FORMAT A10

COLUMN CRS_NAME HEADING 'COURSE|NAME' FORMAT A20

COLUMN DESCRIPTION HEADING 'COURSE|DESCRIPTION' FORMAT A30

COLUMN PROF_NAME HEADING 'PROFESSOR|NAME' FORMAT A30

COLUMN DNAME HEADING 'DEPARTMENT|NAME' FORMAT A30

COLUMN GRADE FORMAT A10

COLUMN ENROLL_TIME HEADING 'ENROLL|TIME' FORMAT A40

COLUMN SDATE HEADING 'START|DATE'

COLUMN EDATE HEADING 'END|DATE'

COLUMN SEMESTERDURATION HEADING 'SEMESTER|DURATION'

COLUMN CUS_CODE HEADING 'CUSTOMER|CODE' FORMAT 9999

COLUMN CUS_NAME HEADING 'CUSTOMER|NAME' FORMAT A20

COLUMN CUS_ADDRESS HEADING 'CUSTOMER|ADDRESS' FORMAT A50

COLUMN CUS_MOBILE HEADING 'CUSTOMER|MOBILE'

SELECT
    *
FROM
    PROFESSOR_DEPARTMENT;

SELECT
    *
FROM
    PROGRAMME;

SELECT
    *
FROM
    STUDENT_VISA;

ALTER SESSION SET NLS_TIMESTAMP_FORMAT = "DD-MM-YY HH24:MI:SS";

SELECT
    *
FROM
    ENROLL;

SELECT
    *
FROM
    STUDENT;

ALTER SESSION SET NLS_TIMESTAMP_FORMAT = "HH24:MI:SS";

SELECT
    *
FROM
    CLASS;

SELECT
    *
FROM
    SEMESTER;

SELECT
    *
FROM
    COURSE;

SELECT
    *
FROM
    DEPARTMENT;

SELECT
    *
FROM
    SCHOOL;

SELECT
    *
FROM
    PROFESSOR;

SELECT
    *
FROM
    CUSTOMER;