DROP TABLE GUEST CASCADE CONSTRAINTS;

DROP TABLE ROOM CASCADE CONSTRAINTS;

DROP TABLE HOTEL CASCADE CONSTRAINTS;

CREATE TABLE
    HOTEL (
        HOTEL_NO NUMBER,
        NAME VARCHAR(50),
        ADDRESS VARCHAR(100),
        CONSTRAINT HOTEL_HOTEL_NO_PK PRIMARY KEY (HOTEL_NO)
    );

CREATE TABLE
    ROOM (
        ROOM_NO NUMBER UNIQUE,
        HOTEL_NO NUMBER,
        TYPE VARCHAR(20),
        PRICE DOUBLE PRECISION,
        CONSTRAINT ROOM_HOTEL_NO_FK FOREIGN KEY (HOTEL_NO) REFERENCES HOTEL (HOTEL_NO),
        CONSTRAINT ROOM_ROOM_NO_PK PRIMARY KEY (HOTEL_NO, ROOM_NO)
    );

CREATE TABLE
    GUEST (
        GUEST_NO NUMBER,
        NAME VARCHAR(50),
        ADDRESS VARCHAR(100),
        PHONE_NUM NUMBER,
        ROOM_NO NUMBER,
        CONSTRAINT GUEST_GUEST_NO_PK PRIMARY KEY (GUEST_NO),
        CONSTRAINT GUEST_ROOM_NO_FK FOREIGN KEY (ROOM_NO) REFERENCES ROOM (ROOM_NO)
    );
