DROP TABLE LOAN CASCADE CONSTRAINTS;

DROP TABLE ACCOUNT CASCADE CONSTRAINTS;

DROP TABLE CUSTOMER CASCADE CONSTRAINTS;

CREATE TABLE CUSTOMER(
    SSN VARCHAR(20),
    NAME VARCHAR(50),
    ADDRESS VARCHAR(100),
    CONSTRAINT CUSTOMER_SSN_PK PRIMARY KEY(SSN)
);

CREATE TABLE ACCOUNT(
    ACC_NO INT,
    BALANCE DOUBLE PRECISION,
    TYPE VARCHAR(10),
    SSN VARCHAR(20),
    CONSTRAINT ACCOUNT_ACC_NO_PK PRIMARY KEY(ACC_NO),
    CONSTRAINT ACCOUNT_SSN_FK FOREIGN KEY(SSN) REFERENCES CUSTOMER(SSN)
);

CREATE TABLE LOAN(
    LOAN_NO VARCHAR(10),
    AMOUNT DOUBLE PRECISION,
    TYPE VARCHAR(10),
    SSN VARCHAR(20),
    DATE_OF_START DATE,
    DATE_OF_END DATE,
    CONSTRAINT LOAN_LOAN_NO_PK PRIMARY KEY(LOAN_NO)
);