-- RETRIEVE THE CUSTOMER WHOSE NAME STARTS WITH S
SELECT
    *
FROM
    CUSTOMER
WHERE
    LOWER(NAME) LIKE('s%');

-- FIND THE CUSTOMER WHO HAVE TAKEN THE LOAN MORE THAN 2 LAKS
SELECT
    NAME
FROM
    CUSTOMER,
    LOAN
WHERE
    AMOUNT > 200000
    AND CUSTOMER.SSN = LOAN.SSN;

-- CUSTOMER NAMES WHO HAVE TAKEN LOAN FROM THE BANK
SELECT
    NAME
FROM
    CUSTOMER,
    LOAN
WHERE
    CUSTOMER.SSN = LOAN.SSN;

-- LIST ALL THE CUSTOMER WHO ARE RESIDING IN CHENNAI
SELECT
    NAME
FROM
    CUSTOMER
WHERE
    LOWER(ADDRESS) LIKE('%chennai%');

-- FIND THE CUSTOMER WHOSE BALANCE IS LESS THAN 1000 RUPEES
SELECT
    NAME
FROM
    CUSTOMER,
    ACCOUNT
WHERE
    BALANCE < 1000
    AND CUSTOMER.SSN = ACCOUNT.SSN;